### ISSUE TITLE
how to get the class name when comparing the images

### ISSUE THREAD

**Issue by Shaam93** [betogaona7/face_recognition#1]
Hi, 
I am doing the similarity comparison on medical data, so it is really important for me to get the label of the origional class when I compare the two images (because I can not recognize if they belong to the same person or not just by looking, with human faces it is very simple).
So I was hoping in the function **plot_imgs** you could help me get the class name on each of the images (for example S1, and S19 instead of Right and left images).  Same case is when you compare the two images at the very end, it would be perfect if we could get the class names too. 

Could you help me please?

**Comment by betogaona7** [comment]
Yeah, of course.

When you create the batch, you get the information that you Dataset class returns. So in your case, I would modify the **getitem** in the Dataset class to return *img1, img2, label, labelimg1, labelimg2*. So when you execute: *batch_sample = next(iter(dataloader))* you will get that information, save it in variables like: *labelimg1 = batch_sample[3]* and send that variable through the **plot_imgs** function to display it as an image label.

**Comment by Shaam93** [comment]
Sorry to comment further on this thread, but just wanted to share more info in case someone else asks about it:
so in getitem after this part:
img1 = Image.open(record1[0])
img2 = Image.open(record2[0])
we add:
labelimg1= record1[1]
labelimg2= record2[1]

and like you said we return like this: 
return img1, img2, label, labelimg1, labelimg2

then for plotting, we do it this way:
class1 = batch_example[3][n_batch]
class2 = batch_example[4][n_batch]
plot_imgs([batch_example[0][n_batch].reshape(105, 105), batch_example[1][n_batch].reshape(105, 105)], [class1, class2])

So thank you again, I would not figure it out without your help! :)
